
##Authenticate user
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "Email":"khan@gmail.com",
    "Password": "123"
}

## Register User
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "Email":"imran@gmail.com",
    "Password": "123"
}

## Get Users
GET http://localhost:3000/api/user/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImtoYW5AZ21haWwuY29tIiwiaWF0IjoxNjUxMTgzOTUxLCJleHAiOjE2NTEyNzAzNTF9.cAwyEv4a5Ai0ut02g52XF-HO8GtYXnNMd93ZfOrH5hw